# Site Settings
name: Luuk Geelen
title: Luuk Geelen
description: Back End Python Engineer
email: luuk.geelen@hotmail.com
url: https://luuckyg.github.io/
baseurl: ''


# Build settings
markdown: kramdown
permalink: pretty

port: 5000

exclude:
  - 'README.md'

sass:
  sass_dir: assets/css
  style: :nested