# ---------------------
# General Settings

name: Luuk Geelen
title: Hi, I'm Luuk!
description: Back End Python Engineer
email: luuk.geelen@hotmail.com
logo: LG

url: https://luuckyg.github.io/
baseurl: ''


menu:
- {name: About, link: '#about'}
- {name: Skills, link: '#skills'}
- {name: Projects, link: '#projects'}
- {name: Contact, link: '#contact'}



# ---------------------
# About Section
about_me: 
  - 'Hi! I am Luuk, a self-taught programmer. Started by using Python for healthcare focussed Machine and Deep Learning projects. Currently, I focus on
  web development and the development of web applications. Creating meaningful and fun projects for everyone to enjoy is what motivates me to keep creating and learning! 
  <br><br>
  Technologies I have been using recently: Python, Javascript, HTML, CSS, JQuery and SQL.
  '


skills:
- {name: Data Analytics, proficiency: 10}
- {name: Machine Learning, proficiency: 8}
- {name: Medical Physics, proficiency: 9}
- {name: Software Development, proficiency: 8}
- {name: Project Management, proficiency: 8}
- {name: Teamwork, proficiency: 9}


languages:
- {name: Python, proficiency: 9}
- {name: SQL, proficiency: 8}
- {name: CSS, proficiency: 8}
- {name: HTML, proficiency: 8}
- {name: JavaScript, proficiency: 8}
- {name: C, proficiency: 7}
- {name: Matlab, proficiency: 7}
- {name: Microsoft, proficiency: 8}
- {name: Linux, proficiency: 8}
- {name: CLI, proficiency: 8}
- {name: Heroku, proficiency: 7}
- {name: Jekyll, proficiency: 7}


frameworks:
- {name: Tensorflow, proficiency: 8}
- {name: PyTorch, proficiency: 8}
- {name: Flask, proficiency: 8}
- {name: Bootstrap, proficiency: 8}



#-------------------------------
# Work Section

projects:
- {name: Smart Tender Analytics Tool,
   folder: proj-1,
   file: work/proj-1.html,
   description: 'Work in progress. Goal: Web application enabling consultants to automatically write and instantly 
                give feedback to clients, regarding their tender.', 
   company: Evolvalor,
   technologies: {'Python', 'CSS', 'HTML', 'JavaScript', 'Flask', 'SQL', 'Bootstrap'},
   time: 'Sep 2019 - now'}
- {name: Automatic Liver Segmentation Using Deep Learning,
   folder: proj-2,
   file: work/proj-2.html,
   description: 'Minor Project. Researching the use of self-attention mechanisms for the segmentation of the liver in CT scans.', 
   company: Quantib,
   technologies: {'Python', 'Tensorflow', 'Numpy', 'Pandas'},
   time: 'Sep 2019 - Jan 2020'}
- {name: Stroke Detection Using Machine Learning,
   folder: proj-3,
   file: work/proj-3.html,
   description: 'Graduation Project. Focussing on stroke detection using Graph Convolutional Neural Networks', 
   company: AMC Amsterdam,
   technologies: {'Python', 'Tensorflow'},
   time: 'Jan 2019 - Jul 2019'}
- {name: Portfolio Website,
   folder: proj-4,
   file: work/proj-4.html,
   description: 'Building a responsive website using HTML, CSS, JavaScript, showcasing my skills and previous work.', 
   company: 'MY OWN COMPANY',
   technologies: {'HTML', 'SASS', 'JavaScript', 'JQuery', 'Jekyll'},
   time: 'June 2020 - now'}
- {name: Study of the Funding Landscape of Digital Health Innovations,
   folder: proj-5,
   file: work/proj-5.html,
   description: 'Market landscape study of the digital health funding landscape.', 
   company: Evolvalor,
   technologies: {'Python'},
   time: 'Jan 2018 - Jul 2018'}


#-------------------------------
# Clients Section

clients:
- {name: 'Scott Summers',
  title: 'Director of Design',
  company: OnToText Ind.,
  img: 'SCOTT',
  quote: '<p><strong>While we all felt that Luuk was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer</p>',
  logo: 'OnToText Ind.'}
- {name: 'Hank McCoy',
  title: 'Eater of Salad',
  company: Antartica Int.,
  img: 'HANK',
  quote: '<p><strong>Working with Luuk was the highlight of my career.</strong></p>',
  logo: 'Antartica Int'}



# ---------------------
# Social

socials:
  - {name: 'Github', icon-id: 'github', link: https://github.com/LuuckyG, class: "fa fa-github"}
  - {name: 'LinkedIn', icon-id: 'linkedin' , link: 'https://www.linkedin.com/in/luuk-geelen-184806a9/', class: "fa fa-linkedin"}
