# ---------------------
# General Settings

name: Luuk Geelen
title: Hi, I'm Luuk!
description: Back End Python Engineer
email: luuk.geelen@hotmail.com
logo: Luuk Geelen

url: https://luuckyg.github.io/
baseurl: ''


menu:
- {name: About, link: '#about'}
- {name: Skills, link: '#skills'}
- {name: Projects, link: '#projects'}
- {name: Clients, link: '#clients'}
- {name: Contact, link: '#contact'}



# ---------------------
# About Section
about_me: 
  - 'Hi! I am Luuk, a <em>self-taught</em> programmer. Started by using Python for <em>healthcare focussed</em> Machine and Deep Learning projects. I currently focus on the development of <em>web applications</em>. Creating <em>meaningful</em> and fun projects for everyone to enjoy is what motivates me to keep creating and learning!'


skills:
- {name: Data Analytics, proficiency: 10, icon: "fa-pie-chart", color: "purple"}
- {name: Machine Learning, proficiency: 8, icon: "fa-cogs", color: "#222"}
- {name: Medical Physics, proficiency: 9, icon: "fa-heartbeat", color: "red"}
- {name: Software Development, proficiency: 8, icon: "fa-code-fork", color: "blue"}
- {name: Project Management, proficiency: 8, icon: "fa-calendar-check-o", color: "#f69c55"}
- {name: Teamwork, proficiency: 9, icon: "fa-comments-o", color: "green"}


technologies:
- {name: Python, proficiency: 9, location: 'python.svg'}
- {name: Tensorflow, proficiency: 8, location: 'tensorflow.svg'}
- {name: Flask, proficiency: 8, location: 'flask.svg'}
- {name: CSS, proficiency: 8, location: 'css.png'}
- {name: HTML, proficiency: 8, location: 'html.svg'}
- {name: JavaScript, proficiency: 7, location: 'javascript.svg'}
- {name: jquery, proficiency: 7, location: 'jquery.gif'}
- {name: SASS, proficiency: 8, location: 'sass.svg'}
- {name: Bootstrap, proficiency: 8, location: 'bootstrap.svg'}
- {name: java, proficiency: 7, location: 'java.svg'}
- {name: 'C++', proficiency: 7, location: 'cplus.svg'}
- {name: postgresql, proficiency: 8, location: 'postgresql2.svg'}
- {name: Matlab, proficiency: 7, location: 'matlab.svg'}
- {name: Heroku, proficiency: 7, location: 'heroku.svg'}
- {name: Jekyll, proficiency: 7, location: 'jekyll.svg'}
- {name: github, proficiency: 9, location: 'github.svg'}
- {name: git, proficiency: 9, location: 'git.svg'}
- {name: Linux, proficiency: 8, location: 'linux.svg'}


#-------------------------------
# Work Section

projects:
- {name: Smart Tender Analytics Tool,
   folder: proj-1,
   link-icon: "fa fa-external-link",
   link: mkbfinancieringshulp.herokuapp.com,
   description: 'Work in progress. Goal: Web application enabling consultants to automatically write and instantly give feedback to clients, regarding their tender.', 
   company: Evolvalor,
   technologies: {'Python', 'CSS', 'HTML', 'JavaScript', 'Flask', 'SQL', 'Bootstrap'},
   time: 'Sep 2019 - now'}
- {name: Automatic Liver Segmentation Using Deep Learning,
   folder: proj-2,
   link-icon: "",
   link: "",
   description: 'Minor Project. Researching the use of self-attention mechanisms for the segmentation of the liver in CT scans.', 
   company: Quantib,
   technologies: {'Python', 'Tensorflow', 'Numpy', 'Pandas'},
   time: 'Sep 2019 - Jan 2020'}
- {name: Stroke Detection Using Machine Learning,
   folder: proj-3,
   link-icon: "",
   link: "",
   description: 'Graduation Project. Focussing on stroke detection using Graph Convolutional Neural Networks', 
   company: AMC Amsterdam,
   technologies: {'Python', 'Tensorflow'},
   time: 'Jan 2019 - Jul 2019'}
- {name: Portfolio Website,
   folder: proj-4,
   link-icon: "",
   link: "",
   description: 'Building a responsive website using HTML, CSS, JavaScript, showcasing my skills and previous work.', 
   company: 'MY OWN COMPANY',
   technologies: {'HTML', 'SASS', 'JavaScript', 'JQuery', 'Jekyll'},
   time: 'June 2020 - now'}
- {name: Study of the Funding Landscape of Digital Health Innovations,
   folder: proj-5,
   link-icon: "",
   link: "#",
   description: 'Market landscape study of the digital health funding landscape.', 
   company: Evolvalor,
   technologies: {'Python'},
   time: 'Jan 2018 - Jul 2018'}


#-------------------------------
# Clients Section

clients:
- {name: 'Mr. K',
  title: 'Co-Founder',
  company: evolvalor,
  img: 'anonymous.png',
  quote: 'We all felt that Luuk was a <strong>great asset to our team</strong> — and really worked hard to understand our products from the point of view of the customer',
  logo: 'evolvalor.png'}
- {name: 'Mr. J',
  title: 'CTO',
  company: Quantib BV,
  img: 'anonymous.png',
  quote: 'Working with Luuk was a great experience. He showed great commitment to our product and not only delivered what we wanted, he also went the extra mile and <strong>the end result was better than we could ever dream of!</strong>',
  logo: 'quantib.png'}
- {name: 'Ms. M',
  title: 'Supervisor',
  company: Amsterdam AMC,
  img: 'anonymous.png',
  quote: 'Luuk showed a <strong>great willingness to learn and develop </strong> himself. This dedication was really noticable in the end result.',
  logo: 'amsterdam_umc.png'}



# ---------------------
# Social

socials:
  - {name: 'Github', icon-id: 'github', link: 'https://github.com/LuuckyG', class: "fa fa-github"}
  - {name: 'LinkedIn', icon-id: 'linkedin' , link: 'https://www.linkedin.com/in/luuk-geelen-184806a9/', class: "fa fa-linkedin"}
